### ISSUE TITLE
Question about Publishing to an direct exchange

### ISSUE THREAD

**Issue by kiequoo** [SpinGo/op-rabbit#42]
I would like to publish messages to a direct exchange with a specific routing key, and have that exchange created if it doesn't exist, but I can't work out the syntax.  My guess is something like:

``` scala
  rabbitControl ! Message("message", "key", Publisher.exchange(Exchange.direct("test")))
```

But that doesn't compile, and I can't work it out by digging in the code even.  Any chance you could help me out?  Thanks!

**Comment by kiequoo** [comment]
PS My use case is that I want my publisher to declare the direct exchange and my consumers to declare queues and bind them to the exchange with specific routing keys.  I'm happy to declare the exchange in the producer before sending the messages, but not quite sure how to do that either.  Op-rabbit is very nice but a few more examples wouldn't go amiss :)

**Comment by timcharper** [comment]
Hi @kiequoo , thanks for letting me know where confusion lies.

Looks like you've found an oversight in the library. I'm terribly sorry about this. I just pushed out v1.1.0 which targets (and requires) Akka 2.4.0.

I'll push out `v1.1.1` and `v1.0.3` which will support this:

```
val keyPublisher = Publisher.exchange(Exchange.direct("test"), "key")
rabbitControl ! Message("message", keyPublisher)
```

Note that for efficiency you should try and re-use publishers, where possible, since the exchange definition is lazily declared on first publish.

**Comment by timcharper** [comment]
`v1.0.3` and `v1.1.1` have been pushed. Thanks for helping to make op-rabbit better!

**Comment by kiequoo** [comment]
Hi Tim, thanks for the update!

**Comment by kiequoo** [comment]
I'm now using v1.1.1 but still having problems, the example you gave above

`val keyPublisher = Publisher.exchange(Exchange.direct("test"), "key")`

Does not compile for me.  

```
Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_66).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import com.spingo.op_rabbit.{Exchange, Publisher}
import com.spingo.op_rabbit.{Exchange, Publisher}

scala> val keyPublisher = Publisher.exchange(Exchange.direct("test"), "key")
<console>:11: error: overloaded method value exchange with alternatives:
  (exchange: com.spingo.op_rabbit.Binding.ExchangeDefinition[com.spingo.op_rabbit.Binding.Concreteness],routingKey: String)com.spingo.op_rabbit.Publisher <and>
  (exchangeName: String,routingKey: String)com.spingo.op_rabbit.Publisher
 cannot be applied to (com.spingo.op_rabbit.Exchange[com.spingo.op_rabbit.Exchange.Direct.type], String)
       val keyPublisher = Publisher.exchange(Exchange.direct("test"), "key")
```

Any ideas?  Am I missing some magic implicit import that will make it compile?

**Comment by timcharper** [comment]
Man, I am so sorry about this. The fault is mine (missing a covariance declaration on ExchangeDefinition...). I'll fix ASAP, add a test, and push out another version.
